### ISSUE TITLE
GLError causing Red Screen with Shaders and Immersive Engineering

### ISSUE THREAD

**Issue by liviniumnetwork** [iPortalTeam/ImmersivePortalsModForForge#11]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

No

### Forge Version

40.1.68

### ImmersivePortals Version

immersive-portals-1.4.9-rc3-mc1.18.2-forge.jar

### Latest Log

Wrong one provided, I will find the correct one and provide when found.

### Steps to Reproduce

1: Use oculus and Rubidium for shaders to work
2: Have immersive portals installed as a mod
3: Load up a world, press K to enable shaders (Mine being ComplementaryShaders_v4.5)
4: Create a nether portal or a portal of your choice, bug happens after portal renders.

### What You Expected

To work as normal with shaders

### What Happened Instead

Everything turned red of the side of the portal you are standing on, see pictures attached.

![Base Profile Screenshot 2022 08 25 - 02 24 47 44](https://user-images.githubusercontent.com/82018786/186733325-0acfc49d-5ef7-47b7-9c10-14a4badc60bc.png)
![Base Profile Screenshot 2022 08 25 - 02 24 55 80](https://user-images.githubusercontent.com/82018786/186733339-b4121e42-3734-46aa-84f1-4bc982e49b50.png)
![Base Profile Screenshot 2022 08 25 - 02 26 09 42](https://user-images.githubusercontent.com/82018786/186733347-68e8442f-7a6e-484a-84b2-662222e54c87.png)
![Base Profile Screenshot 2022 08 25 - 02 26 14 65](https://user-images.githubusercontent.com/82018786/186733351-32ce5437-8a1f-4d9d-838e-6b9b03614160.png)

### Additional Details

Minecraft version is 1.18.2 running the mod pack All The Mods 7, shaders work great with this pack normally.
Happens in both new and old worlds.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
I need the log, if possible also the debug log. Also, I need the exact name and version of the shader you used.

**Comment by liviniumnetwork** [comment]
Here is the link to the shaders, they work for all versions from 1.7.x up to the newest 1.19.x, as I said I am on 1.18.2
https://minecraftshader.com/downloads/complementary

They have not been updated since I started using them.

Sorry I could not find the original log but I was able to recreate the issue, here is the log I have now. I could not however get anything of a debug log.

[latest.log](https://github.com/iPortalTeam/ImmersivePortalsModForForge/files/9440208/latest.log)

**Comment by voxelimprint** [comment]
i have the same issue but i with any shader pack so i was assuming it could be an issue directly with occulus/iris compat but i didnt read your log to see what your using ive attempted pretty much every compatibility and rendering setting to the same results, initially i was thinking the shaders were having a problem with the dimension stack but this seams to be any time you load in any dimension with the shaders enabled you get a full red screen and only see the portals,

**Comment by voxelimprint** [comment]
this is what im running into in log 

Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[17:46:26] [Render thread/WARN]: [<sodium shaders>] Unsupported uniform: vec4 imm_ptl_ClippingEquation
[17:46:26] [Render thread/WARN]: [<sodium shaders>] Unsupported uniform: vec4 imm_ptl_ClippingEquation
[17:46:26] [Render thread/WARN]: [<sodium shaders>] Unsupported uniform: vec4 imm_ptl_ClippingEquation
[17:46:26] [Render thread/INFO]: [Immersive Portals]Switched to compatibility portal rendering mode. Portal-in-portal wont' be rendered
[17:46:26] [Render thread/INFO]: [CHAT] [Immersive Portals]Switched to compatibility portal rendering mode. Portal-in-portal wont' be rendered
[17:46:26] [Render thread/INFO]: switched to renderer class qouteall.imm_ptl.core.compat.iris_compatibility.IrisCompatibilityPortalRenderer
[17:46:26] [Render thread/INFO]: Destroying pipeline OVERWORLD
[17:46:26] [Render thread/INFO]: Destroying pipeline NETHER
[17:46:26] [Render thread/INFO]: Secondary Framebuffer init
[17:46:26] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:46:26] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[17:46:26] [Render thread/WARN]: [<sodium shaders>] Unsupported uniform: vec4 imm_ptl_ClippingEquation
[17:46:26] [Render thread/WARN]: [<sodium shaders>] Unsupported uniform: vec4 imm_ptl_ClippingEquation
[17:46:26] [Render thread/WARN]: [<sodium shaders>] Unsupported uniform: vec4 imm_ptl_ClippingEquation
[17:46:26] [Render thread/WARN]: [gbuffers_flw_flywheel_model_2] Unsupported uniform: vec3 uCameraPos
[17:46:26] [Render thread/WARN]: [gbuffers_flw_flywheel_model_2] Unsupported uniform: mat4 uViewProjection
[17:46:26] [Render thread/WARN]: [gbuffers_flw_flywheel_oriented_3] Unsupported uniform: vec3 uCameraPos
[17:46:26] [Render thread/WARN]: [gbuffers_flw_flywheel_oriented_3] Unsupported uniform: mat4 uViewProjection
[17:46:26] [Render thread/INFO]: Creating pipeline for dimension NETHER
[17:46:27] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[17:46:27] [Render thread/WARN]: [<sodium shaders>] Unsupported uniform: vec4 imm_ptl_ClippingEquation
[17:46:27] [Render thread/WARN]: [<sodium shaders>] Unsupported uniform: vec4 imm_ptl_ClippingEquation
[17:46:27] [Render thread/WARN]: [<sodium shaders>] Unsupported uniform: vec4 imm_ptl_ClippingEquation

**Comment by liviniumnetwork** [comment]
I use oculus, Optifine doesn't work with my game for whatever reason. Crashes the game before boot

**Comment by Nick1st** [comment]
@voxelimprint Can you please list all mods you're using and send me a full log

**Comment by Symm3** [comment]
this happens with immersive engineering installed

**Comment by Lolothepro** [comment]
```
[LWJGL] OpenGL debug message
	ID: 0x502
	Source: API
	Type: ERROR
	Severity: HIGH
	Message: GL_INVALID_OPERATION error generated. Depth formats do not match.
	Stacktrace: MC-BOOTSTRAP/org.lwjgl.opengl@3.3.1+7/org.lwjgl.opengl.GL30C.glBlitFramebuffer(Native Method)
              MC-BOOTSTRAP/org.lwjgl.opengl@3.3.1+7/org.lwjgl.opengl.GL30.glBlitFramebuffer(GL30.java:1838)
              TRANSFORMER/immersive_portals@1.4.10/qouteall.imm_ptl.core.compat.iris_compatibility.IrisCompatibilityPortalRenderer.onBeforeHandRendering(IrisCompatibilityPortalRenderer.java:174)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.handler$zdc000$onRightBeforeHandRendering(GameRenderer.java:2162)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.redirect$zdc000$redirectRenderingWorld(GameRenderer.java:2140)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              java.base/java.lang.reflect.Method.invoke(Method.java:568)
              MC-BOOTSTRAP/fmlloader@1.18.2-40.1.76/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
              cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              java.base/java.lang.reflect.Method.invoke(Method.java:568)
              io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              java.base/java.lang.reflect.Method.invoke(Method.java:568)
              org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
              org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
              org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
              org.polymc.EntryPoint.listen(EntryPoint.java:144)
              org.polymc.EntryPoint.main(EntryPoint.java:74)
[LWJGL] OpenGL debug message
	ID: 0x502
	Source: API
	Type: ERROR
	Severity: HIGH
	Message: GL_INVALID_OPERATION error generated. Depth formats do not match.
	Stacktrace: MC-BOOTSTRAP/org.lwjgl.opengl@3.3.1+7/org.lwjgl.opengl.GL30C.glBlitFramebuffer(Native Method)
              MC-BOOTSTRAP/org.lwjgl.opengl@3.3.1+7/org.lwjgl.opengl.GL30.glBlitFramebuffer(GL30.java:1838)
              TRANSFORMER/immersive_portals@1.4.10/qouteall.imm_ptl.core.compat.iris_compatibility.IrisCompatibilityPortalRenderer.onBeforeHandRendering(IrisCompatibilityPortalRenderer.java:174)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.handler$zdc000$onRightBeforeHandRendering(GameRenderer.java:2162)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.redirect$zdc000$redirectRenderingWorld(GameRenderer.java:2140)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665)
              TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              java.base/java.lang.reflect.Method.invoke(Method.java:568)
              MC-BOOTSTRAP/fmlloader@1.18.2-40.1.76/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
              MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
              cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              java.base/java.lang.reflect.Method.invoke(Method.java:568)
              io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              java.base/java.lang.reflect.Method.invoke(Method.java:568)
              org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
              org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
              org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
              org.polymc.EntryPoint.listen(EntryPoint.java:144)
              org.polymc.EntryPoint.main(EntryPoint.java:74)
```

**Comment by Nick1st** [comment]
@Lolothepro 
@voxelimprint 
@Symm3 

Please send me your full log (uploaded to gist/pastebin) to help me diagnose this further.

**Comment by liviniumnetwork** [comment]
Is there anything else you need from me @Nick1st

**Comment by Nick1st** [comment]
> Is there anything else you need from me @Nick1st 

No, I got everything I need for now, thanks for the report.

**Comment by liviniumnetwork** [comment]
Awesome, I'll leave this open as I'm not the only one with the problem

**Comment by Lolothepro** [comment]
https://mclo.gs/KgA3cRr
https://paste.gg/p/anonymous/26d2285564a34507aeea9abf5188c5a5
https://hst.sh/ihadujefod
https://0x0.st/of3u.txt

**Comment by voxelimprint** [comment]
I'm at work but I'll do that as soon as I get home. I had run it just with
this mod and rubbidium, Oculus for shaders.

**Comment by Nick1st** [comment]
I'm going to use this issue as my notes section on this, so feel free to ignore further messages in this thread.

It seems that there are actually two spots causing this issue. Both are in an Iris Compatibility Renderer, one in the method called without any portals visible, the other one in the method for rendering when a portal is visible.

Ok, so the method I'm going to focus on first, is the one without visible portals. (https://github.com/iPortalTeam/ImmersivePortalsModForForge/blob/b2c68ee818ed4cc91615de3a824c32d4947e5a8f/imm_ptl_core/src/main/java/qouteall/imm_ptl/core/compat/iris_compatibility/IrisCompatibilityPortalRenderer.java#L163-L194)

Diagnosing the issue: `GL_INVALID_OPERATION error generated. Depth formats do not match.` 
Quick-Random-Doc-Link: https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBlitFramebuffer.xhtml 

_Edit:_ Removing the `GL11.GL_DEPTH_BUFFER_BIT` form the Mask actually seems to fix the red screen, though it of course causes problems when looking at a portal.

**Comment by Nick1st** [comment]
Immersive Engineering contains some core shaders, having a look at https://github.com/IrisShaders/Iris/issues/1403 this might cause issues.

Note, there is a mismatch in the iris DepthBuffer Version between the Main Target and the SecondaryFrameBuffer and I'm not sure if that's normal, but I suppose not.

**Comment by Nick1st** [comment]
Additional Debug Log:
```
java.lang.Throwable
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.platform.GlDebug.handler$zcg000$onLogging(GlDebug.java:522)
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.platform.GlDebug.printDebugLog(GlDebug.java:117)
	at MC-BOOTSTRAP/org.lwjgl.opengl/org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39)
java.lang.IllegalStateException: Tried to use destroyed RenderTargets
	at TRANSFORMER/oculus@1.2.5a/net.coderbot.iris.rendertarget.RenderTargets.get(RenderTargets.java:99)
	at TRANSFORMER/oculus@1.2.5a/net.coderbot.iris.samplers.IrisSamplers.lambda$addRenderTargetSamplers$0(IrisSamplers.java:42)
	at TRANSFORMER/oculus@1.2.5a/net.coderbot.iris.gl.sampler.SamplerBinding.update(SamplerBinding.java:19)
	at TRANSFORMER/oculus@1.2.5a/net.coderbot.iris.gl.program.ProgramSamplers.update(ProgramSamplers.java:43)
	at TRANSFORMER/oculus@1.2.5a/net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkShaderInterface.setup(IrisChunkShaderInterface.java:73)
	at TRANSFORMER/rubidium@0.5.4/me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.handler$bff000$iris$begin(ShaderChunkRenderer.java:569)
	at TRANSFORMER/rubidium@0.5.4/me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java)
	at TRANSFORMER/rubidium@0.5.4/me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at TRANSFORMER/rubidium@0.5.4/me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:294)
	at TRANSFORMER/rubidium@0.5.4/me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.LevelRenderer.renderChunkLayer(LevelRenderer.java:7945)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1388)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1073)
	at TRANSFORMER/immersive_portals@0.0NONE/qouteall.imm_ptl.core.render.MyGameRenderer.lambda$switchAndRenderTheWorld$0(MyGameRenderer.java:177)
	at TRANSFORMER/immersive_portals@0.0NONE/qouteall.imm_ptl.core.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:175)
	at TRANSFORMER/immersive_portals@0.0NONE/qouteall.imm_ptl.core.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:65)
	at TRANSFORMER/immersive_portals@0.0NONE/qouteall.imm_ptl.core.compat.iris_compatibility.IrisCompatibilityPortalRenderer.invokeWorldRendering(IrisCompatibilityPortalRenderer.java:135)
	at TRANSFORMER/immersive_portals@0.0NONE/qouteall.imm_ptl.core.render.PortalRenderer.renderPortalContent(PortalRenderer.java:188)
	at TRANSFORMER/immersive_portals@0.0NONE/qouteall.imm_ptl.core.compat.iris_compatibility.IrisCompatibilityPortalRenderer.doRenderPortal(IrisCompatibilityPortalRenderer.java:100)
	at TRANSFORMER/immersive_portals@0.0NONE/qouteall.imm_ptl.core.compat.iris_compatibility.IrisCompatibilityPortalRenderer.renderPortals(IrisCompatibilityPortalRenderer.java:207)
	at TRANSFORMER/immersive_portals@0.0NONE/qouteall.imm_ptl.core.compat.iris_compatibility.IrisCompatibilityPortalRenderer.onBeforeHandRendering(IrisCompatibilityPortalRenderer.java:185)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.handler$zdc000$onRightBeforeHandRendering(GameRenderer.java:2174)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1073)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.redirect$zdc000$redirectRenderingWorld(GameRenderer.java:2152)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:847)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.runTick(Minecraft.java:1070)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.run(Minecraft.java:668)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.60/net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:24)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```

**Comment by Lolothepro** [comment]
The issue is that the new versions of Iris contain a lot of bug fixes, but Oculus is not updated too much and no longer contains the Iris fixes.

**Comment by Nick1st** [comment]
Ok, so the issue is actually caused by Immersive Engineering using stencil buffers, creating a mismatch in the Depth formats of the target and secondary frame buffer used by Immersive Portals. (There is some guessing in there, so take this with a grain of salt.)

Setting 
```
#Set to false to disable the stencil buffer. This may be necessary on older GPUs.
stencilBufferEnabled = false
```
in Immersive Engineerings config will fix the issue for now, while I'm trying to patch this.

Note to myself: https://github.com/IrisShaders/Iris/commit/f5d3a6dc4a51e014d618b4dfed6092ac62a82e40

**Comment by qouteall** [comment]
I am planning to use a different way to copy stencil to get better compatibility with some videocards.

**Comment by Nick1st** [comment]
Can someone check if this still happens in the 1.19 alpha?

**Comment by Syclusion** [comment]
> Can so
![2023-01-12_11 13 48](https://user-images.githubusercontent.com/98832017/212121195-5870ef58-b72f-4269-8449-9224dd53096e.png)
meone check if this still happens in the 1.19 alpha?

Just tried it with newest 1.19.2 of Immersive portals and Immersive engineering with stencils off, seems fixed. Hopefully this can get into the 1.18.2 version as well!

**Comment by HoottooH** [comment]
Any update on this? I'm getting the same issue even with the most recent 1.19.2 version (2.3.3.) as well as immersive engineering (9.2.0-162) regardless of whether stencils are off or on
_Sorry if this is necro posting at this point_

**Comment by Xplodin** [comment]
edit nvm works with astralex bsl and stencils OFF for immersive engineering

**Comment by jjjworley** [comment]
Thank you for figuring this problem out. I am using 1.19.2 and I had the red world problem, where iris would go into compatibility mode and turn the whole world red. I disabled the stencil buffer and now everything seems to work correctly. This is my first time using immersive portals, and I am highly impressed! I am using Oculus and Rubidium, because Immersive Engineering said it was incompatible with Optifine. Little did I know! Thank you again, I know I will use your mod for a long time from now.

**Comment by KusanagiRyu** [comment]
I'm playing All the Mods 8, installed Immersive Portal and using ComplementaryShaders v4.7.1 also having the red screen regardless of whether stencils are off or on.

**Comment by liviniumnetwork** [comment]
Hey @Nick1st Is this still needed as open or is all fixed and done now? Sorry for the tag

**Comment by Nick1st** [comment]
Not sure? I think the issue still exists if stencils are on?

**Comment by Syclusion** [comment]
Def still broken

**Comment by Nightmar0** [comment]
Will this be fixed in 1.20.1? Btw, Idk who is updating the mod for forge 1.20.1, but to them I say, "THANK YOU SOOO MUCH!! 😊😊😊😊😊😊😊😊😊

**Comment by YY40444** [comment]
> 谢谢你帮我解决了这个问题。我用的是1.19.2版本，遇到过红色世界问题，虹膜会进入兼容模式，整个世界变成红色。我禁用了模板缓冲区，现在一切似乎都正常工作了。这是我第一次使用沉浸式传送门，我非常满意！我用的是Oculus和Rubidium，因为Immersive Engineering说它们和Optifine不兼容。我完全没想到！再次感谢你，我知道我以后会用你的模组很久。

Hi, I want to know how you solved it, because it seems that I encountered the same problem as you and am using the same mods. But the problem still exists after I tried turning off the template buffer.
