### ISSUE TITLE
[Bug] Connectivity / XL packages

### ISSUE THREAD

**Issue by woliver99** [iPortalTeam/ImmersivePortalsModForForge#21]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.73

### ImmersivePortals Version

1.4.10-mc1.18.2

### Latest Log

https://gist.github.com/woliver99/1dc09493e8c0c0142b9580c75832b389

### Steps to Reproduce

1. Start Modpack
2. Join Server
3. Get Kicked For Bad Packet

### What You Expected

Join server successfully

### What Happened Instead

Kicked out of server due to invalid packet

### Additional Details

It works fine in single-player it's only when I join a server. I have a few mods that are incompatible so that could be why ex: create rubidium. But it has to do with a bad packet when joining a server. Anyway, I'm not expecting this to get fixed I just want you to be aware of the issue.
All Mods/Logs: https://drive.google.com/drive/folders/1Ma-56yIXyBjx8Q3jbvUDMFHYp7-dXKni?usp=sharing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Please try without connectivity.

**Comment by woliver99** [comment]
So idk what happened but i think i accidentally deleted all my client side mods including connectivity but it started to work if you want when im back at my pc i can test it with connectivity and see if thats the problem

**Comment by woliver99** [comment]
Yea it was connectivity, I got the same error with it on

**Comment by Lolothepro** [comment]
fixed (when Immersive Portal For Forge will have a version 1.19.2)

**Comment by masonbesmer** [comment]
Will this not be fixed below 1.19.2?

**Comment by DavidTs93** [comment]
Still happening while using the latest Connectivity and Immersive Portals versions.

**Comment by Xplodin** [comment]
unfortunately this error stems from connectivity and MixinClientboundCustomPayloadPacket
changing the code to 
private int modifySizeLimitWhenReadingPacket(int value) {
        return 233333333;
    }

previous code -> //private int modifySizeLimitWhenReadingPacket(int oldValue) {

got this to work with packetsizedoubler mod instead of connectivity since its closed source. (oof)

I had to modify both mods but would crash once switching dimensions

**Comment by 5stigma** [comment]
Will there be any solution?
I read in Connectivity issues that compatibility will not be ported to forge 1.18.2.

**Comment by Nick1st** [comment]
Happens also with XL packages (There's a crash #113 ) due to the same mixin.
